# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAtualizarkitnet():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_atualizarkitnet(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-neutral-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-2:nth-child(4) .border-repimehardblue:nth-child(1) > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-span-1:nth-child(2) > .rounded-xl").click()
    self.driver.find_element(By.CSS_SELECTOR, ".disable\\3Aopacity-70").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".disable\\3Aopacity-70")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "residencia.end_rua").click()
    self.driver.find_element(By.ID, "residencia.end_rua").send_keys("Jardim das Flores")
    self.driver.find_element(By.ID, "residencia.end_bairro").send_keys("Vista ALegre")
    self.driver.find_element(By.ID, "residencia.end_bairro").click()
    self.driver.find_element(By.ID, "residencia.end_bairro").send_keys("Vista Alegre")
    self.driver.find_element(By.ID, "residencia.end_complemento").click()
    self.driver.find_element(By.ID, "residencia.end_complemento").send_keys("Prédio")
    self.driver.find_element(By.ID, "residencia.end_cep").send_keys("13990000")
    self.driver.find_element(By.ID, "residencia.end_numero").send_keys("151")
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-qbdosj-Input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-1fdsijx-ValueContainer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1fdsijx-ValueContainer").click()
    self.driver.find_element(By.ID, "residencia.end_numero").send_keys("151")
    self.driver.find_element(By.ID, "react-select-2-input").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".disable\\3Aopacity-70:nth-child(2)").click()
    self.driver.find_element(By.ID, "residencia.nome").click()
    self.driver.find_element(By.ID, "residencia.tempo_de_contrato").send_keys("5")
    self.driver.find_element(By.ID, "residencia.tem_garagem").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".disable\\3Aopacity-70:nth-child(2)").click()
  
